version: '3.9'
services:
  db:
    container_name: psql
    image: postgres:latest
    restart: always
    ports:
      - '5432:5432'
    environment:
      - POSTGRES_DB=products
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=mysecretpassword
    volumes:
      # - db:/var/lib/postgresql/data
      - ./products:/home/data
      - ./db/init.sql:/docker-entrypoint-initdb.d/create_tables.sql
  api:
    tty: true
    container_name: products-api
    build:
      context: ./
      # target: production
      dockerfile: Dockerfile
    image: node:latest
    depends_on:
      - db
    ports:
      - 3030:3000
    environment:
      # NODE_ENV: production
      DB_HOST: host.docker.internal
      DB_USER: postgres
      DB_PASSWORD: postgres
      DB_NAME: postgres
    links:
      - db
    volumes:
      - ./server:/server
# volumes:
#   db:
#     driver: local